migrate:
  from: github
  to: gitee
  clone_dir: ""
  # 默认迁移所有代码仓，可以设置 repos 迁移特定的代码仓
  # repos:
  #   - repo_a
  #   - repo_b

gitee:
  provider: gitee
  base_api: https://gitee.com/api/v5
  ssh_prefix: git@gitee.com
  https_prefix: https://gitee.com
  username: ""
  token: ""

github:
  provider: github
  base_api: https://api.github.com/graphql
  ssh_prefix: git@github.com
  https_prefix: https://github.com
  username: ""
  token: ""
  use_https: true

gitlab:
  provider": gitlab
  base_api: https://gitlab.com/api/v4
  ssh_prefix: git@gitlab.com
  https_prefix: https://gitlab.com
  username: ""
  token: ""

coding:
  provider: coding
  base_api: https://{your-team}.coding.net
  ssh_prefix: git@e.coding.net
  https_prefix: https://e.coding.net
  username: ""
  token: ""
  org_name: ""
  is_org: false
  use_web_base_api: true
  use_https: true
  web_cookie: ""

# 腾讯工蜂 https://code.tencent.com/
gongfeng:
  provider: gongfeng
  base_api: https://code.tencent.com/api/v3
  ssh_prefix: git@git.code.tencent.com
  https_prefix: https://git.code.tencent.com
  username: ""
  token: ""

gitea:
  provider: gitea
  base_api: https://gitea.com/api/v1
  ssh_prefix: git@gitea.com
  https_prefix: https://gitea.com
  username: ""
  token: ""

e_gitee_v8:
  provider: e_gitee_v8
  base_api: https://api.gitee.com/enterprises
  https_prefix: https://gitee.com
  enterprise_id: ""
  token: ""
  token_user: ""
  use_https: true
